{% set name = "dbt" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c76857f40e1cc839bfbbc53e87dc3ce1090bc369cc8a5d38846988628a164b5d
    folder: dbt
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-core/{{ name }}-core-{{ version }}.tar.gz
    sha256: 90bde01d078b1d673dc490b9defff07e7f3b702b920c65feae6fb27e07ce73d2
    folder: dbt-core
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-postgres/{{ name }}-postgres-{{ version }}.tar.gz
    sha256: 78eac4ba58b1204071de84db69ac44dc68372b680da39879428261338f122992
    folder: dbt-postgres
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-redshift/{{ name }}-redshift-{{ version }}.tar.gz
    sha256: 6419212b1c540358f2b9b32408fce6beac9387c40f810d98df7804395e9273bf
    folder: dbt-redshift
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-bigquery/{{ name }}-bigquery-{{ version }}.tar.gz
    sha256: e22442f00fcec155dcbfe8be351a11c35913fb6edd11bd5e52fafc3218abd12e
    folder: dbt-bigquery
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-snowflake/{{ name }}-snowflake-{{ version }}.tar.gz
    sha256: a263274d6af430edfe33cf57b44c7eba58a73017ec8b1c82cb30b25e42be9a1c
    folder: dbt-snowflake

build:
  number: 0
  noarch: python

outputs:
  - name: dbt
    build:
      noarch: python

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("dbt-core", exact=True) }}
        - {{ pin_subpackage("dbt-bigquery", min_pin='x.x', max_pin='x.x') }}
        - {{ pin_subpackage("dbt-postgres", min_pin='x.x', max_pin='x.x') }}
        - {{ pin_subpackage("dbt-redshift", min_pin='x.x', max_pin='x.x') }}
        - {{ pin_subpackage("dbt-snowflake", min_pin='x.x', max_pin='x.x') }}

    test:
      imports:
        - dbt
      commands:
        - pip check
      requires:
        - pip


  - name: dbt-core
    build:
      noarch: python
      entry_points:
        - dbt = dbt.main:main
      script: python -m pip install --no-deps  -vv ./dbt-core

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        # Update the version number in URL before verifying dependencies.
        # https://github.com/dbt-labs/dbt-core/blob/v1.0.0/core/setup.py
        - jinja2 ==2.11.3
        - agate >=1.6,<1.6.4
        - click >=8,<9
        - colorama >=0.3.9,<0.4.5
        - hologram ==0.0.14
        - isodate >=0.6,<0.7
        - logbook >=1.5,<1.6
        - mashumaro ==2.9
        - minimal-snowplow-tracker ==0.0.2
        - networkx >=2.3,<3
        - packaging >=20.9,<22.0
        - sqlparse >=0.2.3,<0.5
        - dbt-extractor ==0.4.0
        - typing-extensions >=3.7.4,<3.11
        - werkzeug >=1,<3

        # According to setup.py, "the following are all to match snowflake-connector-python"
        # - requests <3.0.0
        # - idna >=2.5,<4
        # - cffi >=1.9,<2.0.0

    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
        - dbt --help
      requires:
        - pip


  - name: dbt-postgres
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./dbt-postgres

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        # Update the version number in URL before verifying dependencies.
        # https://github.com/dbt-labs/dbt-core/blob/v1.0.0/plugins/postgres/setup.py
        - {{ pin_subpackage("dbt-core", exact=True) }}
        - psycopg2-binary ~=2.8

    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
      requires:
        - pip


  - name: dbt-redshift
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./dbt-redshift

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        # Update the version number in URL before verifying dependencies.
        # https://github.com/dbt-labs/dbt-redshift/blob/v1.0.0/setup.py
        - boto3 >=1.4.4,<2.0.0
        - {{ pin_subpackage("dbt-core", exact=True) }}
        - {{ pin_subpackage("dbt-postgres", min_pin='x.x', max_pin='x.x') }}

    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
      requires:
        - pip

  - name: dbt-bigquery
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./dbt-bigquery

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        # Update the version number in URL before verifying dependencies.
        # https://github.com/dbt-labs/dbt-bigquery/blob/v1.0.0/setup.py
        - {{ pin_subpackage("dbt-core", exact=True) }}
        - protobuf >=3.13.0,<4
        - google-cloud-core >=1.3.0,<3
        - google-cloud-bigquery >=1.25.0,<3
        - google-api-core >=1.16.0,<3
        - googleapis-common-protos >=1.6.0,<2

    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
      requires:
        - pip

  - name: dbt-snowflake
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./dbt-snowflake

    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        # Update the version number in URL before verifying dependencies.
        # https://github.com/dbt-labs/dbt-snowflake/blob/v1.0.0/setup.py
        - {{ pin_subpackage("dbt-core", exact=True) }}
        - snowflake-connector-python>=2.4.1,<2.8.0
        # For "secure-local-storage" extras_require https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py:
        - keyring !=16.1.0,<24.0.0
        - requests <3.0.0
        - cryptography >=3.2,<4

    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/dbt-labs/dbt
  summary: With dbt, data analysts and engineers can build analytics the way engineers build applications.
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - maresb
    - thewchan
