{% set name = "dbt-core" %}
{% set version = "1.8.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dbt-labs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9dec1c3c9e8558311848830ccab8e6d4909a54262a3285a2962bab1f10226921
  patches:
    - patches/0001-Downgrade-protobuf-version.patch

build:
  number: 0
  entry_points:
    - dbt = dbt.cli.main:cli
  script: {{ PYTHON }} -m pip install ./core -vv --no-deps --no-build-isolation
  # logbook not avaliable on python3.12
  skip: True  # [py<39 or py>311]
  skip: True  # [s390x]

requirements:
  build: 
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    # Mashumaro is installed as "mashumaro[msgpack]", so the following comes from
    # the "extras_require" section of https://github.com/Fatal1ty/mashumaro/blob/master/setup.py
    - msgpack-python >=0.5.6
    - agate >=1.7.0,<1.10
    - jinja2 >=3.1.3,<4
    - mashumaro >=3.9,<4.0
    - logbook >=1.5,<1.6
    - click >=8.0.2,<9.0
    - networkx >=2.3,<4.0
    - protobuf >=4.0.0,<5.0
    - requests <3.0.0
    - pathspec >=0.9,<0.13
    - sqlparse >=0.5.0,<0.6.0
    - dbt-extractor >=0.5.0,<=0.6
    - minimal-snowplow-tracker >=0.0.2,<0.1
    - dbt-semantic-interfaces >=0.5.1,<0.6
    - dbt-common >=1.0.4,<2.0
    - dbt-adapters >=1.1.1,<2.0
    - packaging >20.9
    - pytz >=2015.7
    - pyyaml >=6.0
    - daff >=1.3.46
    - typing_extensions >=4.4

# Skip tests reason: Have dependencies on the dbt-postgres
# But dbt-postgres can`t build without dbt-core.
# https://github.com/dbt-labs/dbt-postgres/blob/v1.9.0/pyproject.toml#L29
#{% set ignore_tests = "" %}
#{% set ignore_tests = " --ignore=tests/functional/adapter/unit_testing/test_unit_testing.py" %}
#{% set ignore_tests = ignore_tests + " --ignore=tests/unit/config/test_profile.py" %}
#{% set ignore_tests = ignore_tests + " --ignore=tests/unit/context/test_context.py" %}
#{% set ignore_tests = ignore_tests + " --ignore=tests/unit/graph/test_selector.py" %}
#{% set ignore_tests = ignore_tests + " --ignore=tests/unit/task/test_retry.py" %}

test:
  source_files:
    - tests
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
    - dbt --help
    #- pytest -vvv {{ ignore_tests }} tests
  requires:
    - pip
    - pytest
    - hypothesis

about:
  home: https://github.com/dbt-labs/dbt
  summary: With dbt, data analysts and engineers can build analytics the way engineers build applications.
  license: Apache-2.0
  license_file: License.md
  license_family: Apache
  description: dbt enables data analysts and engineers to transform their data using the same practices that software engineers use to build applications.
  dev_url: https://github.com/dbt-labs/dbt-core
  doc_url: https://www.getdbt.com/

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - maresb
    - thewchan
