{% set name = "dbt-core" %}
{% set version = "1.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dbt-labs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7a7188d1f3bedc28fa4399d9908718e0569623b5dd6af0ef1ec7fbcd00e1803f
  patches:
    - patches/0001-Change-protobuf-version.patch

build:
  number: 0
  entry_points:
    - dbt = dbt.cli.main:cli
  script: {{ PYTHON }} -m pip install ./core -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  build: 
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - wheel
    - setuptools >=40.1.0
  run:
    - python
    - msgpack-python >=0.5.6
    - agate >=1.7.0,<1.10
    - jinja2 >=3.1.3,<4
    - mashumaro >=3.9,<3.15
    - click >=8.0.2,<9.0
    - jsonschema >=4.19.1,<5.0
    - networkx >=2.3,<4.0
    - protobuf >=5.0,<7.0
    - requests <3.0.0
    - snowplow-tracker >=1.0.2,<2.0
    - pathspec >=0.9,<0.13
    - sqlparse >=0.5.0,<0.6.0
    - dbt-extractor >=0.5.0,<=0.6
    - dbt-semantic-interfaces >=0.9.0,<0.10
    - dbt-common >=1.27.0,<2.0
    - dbt-adapters >=1.15.2,<2.0
    - dbt-protos >=1.0.346,<2.0
    - pydantic <3
    - packaging >20.9
    - pytz >=2015.7
    - pyyaml >=6.0
    - daff >=1.3.46
    - typing_extensions >=4.4

# AssertionError: assert 'doesnt/actually/exist\\target' == 'doesnt/actually/exist/target'
# - doesnt/actually/exist/target
# ?                      ^
# + doesnt/actually/exist\target
{% set deselect_tests = "" %}
{% set deselect_tests = " --deselect=tests/unit/test_deps.py::TestTarballPackage::test_fetch_metadata" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_functions.py::test_setup_event_logger_specify_max_bytes" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_graph_selection.py::test_run_specs" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_internal_deprecations.py::test_deprecated_func" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_parser.py::GenericTestParserTest::test_basic" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_proto_events.py::test_extra_dict_on_event" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/cli/test_flags.py::TestFlags::test_from_dict__build" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/config/test_project.py::TestProjectMethods::test_generic_test_paths" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/config/test_project.py::TestProjectMethods::test_fixture_paths" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/config/test_project.py::TestProjectMethods::test_project_target_path" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/parser/test_manifest.py::TestPartialParse::test_partial_parse_file_path" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/parser/test_partial.py::test_schedule_nodes_for_parsing_basic" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/parser/test_partial.py::test_schedule_macro_nodes_for_parsing_basic" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/parser/test_partial.py::TestFileDiff::test_build_file_diff_basic" %}  # [win]

test:
  source_files:
    - tests
    - core
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
    - dbt --help
    - python -m pytest -vvv {{ deselect_tests }} tests/unit
  requires:
    - pip
    - pytest >=7.4,<8.0
    - pytest-mock
    - dbt-postgres
    - hypothesis
    - freezegun

about:
  home: https://github.com/dbt-labs/dbt
  summary: With dbt, data analysts and engineers can build analytics the way engineers build applications.
  license: Apache-2.0
  license_file: License.md
  license_family: Apache
  description: |
    dbt enables data analysts and engineers to transform their data using the same practices that software engineers use to build applications.
  dev_url: https://github.com/dbt-labs/dbt-core
  doc_url: https://docs.getdbt.com

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - maresb
    - thewchan
  skip-lints:
    - patch_unnecessary
    - missing_imports_or_run_test_py
    - missing_pip_check
    - missing_tests
