# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KPBsl4+E99ZMho2NEKovtcFxIqZkh2ltgSoxzqMzTrEagujgybGU38nAg+zB0LsiIy2PSDjy4rqnJ2DlSv692jqm8cidkcGA/zTkNkw2wpcXkQgHixZVkqbsM8sGURUpnmsYqp26AgU+AaLp7208yjYhTazkfThimNJzTMYvgzhotT8apRmK2r13zrTETijqOYLjzCT+IOwFreSnBb/VA84zTf5GsGlVAhCxVY4MxlIe/5dah6tr5HLX4pHM9LBHW9ODkb5dw0YLmpY1TlXJWVjYsSUGcc+JFJP/tBwdzd7Vktg+TGNOQ1wVcdFRG6aYFV/ZwR9nfBTNM7nd5TiXEoGoiJ281nkrCoFzseBqGy9v/JVzx/N2nN5z17k4agwtWVkmj7G4gHWEOz86msF8mE8p9xt2ONEZYF2Bn+prGw+XZKRbpWDYRmRHnOSOFdX9V/XiWESc7Vxqmbl0eecqqwinaFKz8RHU61H65SeZZQo8iPN9lWUDIK9DRZ2syJ2RFMaz2GsQo9Lec9+OfQhwCLak9oG7xLFuaDL9spO4j6AC87TUPRGWPJsgmBv6KuC9ZUEQ1KQsxHyxEhg0KmXxeT1R+eYEQUPqN2Efcbh5386mLw+IqI3UFfGh3nTS2Z53k4Bz1kYdl+f8nnZjlW+PwquW9p2naLKk1KFn5iBLgNo="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
