# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HbiTd3Vxg/qEkrnVvVldpvA7ijY9/VzRpukTG+kZSBVNpOMr5yjejGFeC/Z1dHzzDawkdzxoMDt0f8xq+yVCCzEB5vMX+hIRORUw8GxEOPGUOSYb7rBCxJX5MLWq1kFoF7mj4nbWvQJ2ws2DoIA0IidefrNktYrkZw8zKQqOVNSgSPAARR7igS3r2zafGfiWca6SkwCXBpxgVherLLZjbpBmiKPfTToecPz4HFy2YghYZkBC3h/Tw+NmB2+oPwZphkR+W5KLnmzor4Iodf1N79WxgLxmcUo7DNTPEsdiqpRhnqM4Q43oAFOjSku0mEgXoLInNfcYztygqfs4izCDXLUeWzGDOYedTGVBGSQP20mX7+9fkdCuSKhRvTo+YMn6mFdU8OBUSf6CExx6ix+cSHCSbRoz42zV22QQlEQn1+3gBs3ycusczLj44AunzCgOkMX7HVkXmGlf7zymJ32Om6+jVomAEHoIj173McvF3m8ctmrmDatZt1XeVKyGf7j8M+egCCQ+wyVqc7LQuycwEv9mJz2RiEJGXtYgrOSG/v0TH0hFHL4hXZ+3a85C/cCr4mrU3vWjT04w4vSeX8AXdVJGlXC5QDXFmgVd4o7kUM8omGU16xaeuV0egb/KTI9xw+rJckRpU3EGgZzI7YAOLadIZ8UbhGVClaDVamlbR2k="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
