travis:
  secure:
    BINSTAR_TOKEN: yImTDeG+liUiIqRL79WaUjlUhd1KBlmvT0UaT4ni/yatMUT/KM66RwIIYRyGfINo08hYgnvsMnMs3hZI4DxQ9uMU7Z1XfDraZB1X3RA7ZRAAT48OXMQ7qjMdyFD0SicX/lqDxGdLOJsb6D3/bQqcU20Mnk29ZR+L/PDE6ysRvccufMrgo7jZ6rxw29CgYZEsJqiRRW4QvCikH2Nx8v/nJhPLEuJhZH1XVxJ2rDdmNvwcYZWHQTgvv0+tKqW5QccxjbffQhXY4Ak/r0Eab2D0CoWFsEqlI1M21oA2yhlF9Ykds1oJxfJLiuZ2psrRAkQg5Mch0/YjBM5Y2EK704WrMVFRtHqsyXVPk20qMVh74tE0Y4sNWNFBF8QuKUmlvp+bG5zddcVGNj7a69LDSIiUBETZqy6Aazqym0dNIgxupfEkXQox1pYzKZ47Vfq8mMlY5U1TaCrWjRmaKKXsJMnzbgatbYGtRr8jWIPYFlT09gyardbofm7h6JjXEOCXo9j8IKpHO+s644LwzuENuUeTiYQSYcuyHll7NlBPBiyQ3Gu+2IzThQE90tpkeaEtL/+2inymh+kcxG2KO8Fj33SOU7PrW1nucFIQCN9flMb69z426JhZgxKfhbJAhR2JGXzsUEveZU2UNKtkHB4CoROsol2jdr1pt/QM8wsQaod+zU4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
