travis:
  secure:
    BINSTAR_TOKEN: HbiTd3Vxg/qEkrnVvVldpvA7ijY9/VzRpukTG+kZSBVNpOMr5yjejGFeC/Z1dHzzDawkdzxoMDt0f8xq+yVCCzEB5vMX+hIRORUw8GxEOPGUOSYb7rBCxJX5MLWq1kFoF7mj4nbWvQJ2ws2DoIA0IidefrNktYrkZw8zKQqOVNSgSPAARR7igS3r2zafGfiWca6SkwCXBpxgVherLLZjbpBmiKPfTToecPz4HFy2YghYZkBC3h/Tw+NmB2+oPwZphkR+W5KLnmzor4Iodf1N79WxgLxmcUo7DNTPEsdiqpRhnqM4Q43oAFOjSku0mEgXoLInNfcYztygqfs4izCDXLUeWzGDOYedTGVBGSQP20mX7+9fkdCuSKhRvTo+YMn6mFdU8OBUSf6CExx6ix+cSHCSbRoz42zV22QQlEQn1+3gBs3ycusczLj44AunzCgOkMX7HVkXmGlf7zymJ32Om6+jVomAEHoIj173McvF3m8ctmrmDatZt1XeVKyGf7j8M+egCCQ+wyVqc7LQuycwEv9mJz2RiEJGXtYgrOSG/v0TH0hFHL4hXZ+3a85C/cCr4mrU3vWjT04w4vSeX8AXdVJGlXC5QDXFmgVd4o7kUM8omGU16xaeuV0egb/KTI9xw+rJckRpU3EGgZzI7YAOLadIZ8UbhGVClaDVamlbR2k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
