travis:
  secure:
    BINSTAR_TOKEN: 8JX5CZLCbhBYKvhieBkAEZbC9PXVeRanSrUB4SdxrpR2oKAClngYWtMDa1jQHJ2Mv8n97SZ27k0KGGiDX3LdPKslXQDLcH0U3kEVqLmNSIQnT0xv6N3ozMPuRuy6JODgMtsTaWByXx7XiTLxnUC/p33i7TQFitGrrJAjC7NvnHIrfMN8MQIUeGvpbS4472jf6YesJJ0DBDFw9GSCDpVgKwfyOZuc54gE8/aRH0LtYhnuWprRuoQEgswUnV30erYclRDgiig5yD4regDIWYSOSloRfTiRhAiVv+p6vEme+03SMaBkxG7IOcJf2dpNLAwCBQhzHWszsPtPaXqEnCIH2bjsPsc2Kjg9RmnJnTjgiuzmc+xPFfNRoGl93ArmaV+Ol2OHOopues1mTV//MpFS7p9EQ/dpCX4Cel9/8OhzKzWqpObogNwhFnUeOcHJUHk62V/rIAVmdVTuFBtk7E4+tQpYIfYZm9bqJQ5E6bnPXbD9PMMQUzw15e4L+UsXFqJRpp/XqTvH5O4YIQJRX1kc8dPJ6VAv78N0R0lFJdltvID9l63Tcq1eSu+nbdlZ8MVIJck6cSxrlkqWuLs0XWApPnwdzo+BQRj4w1luEG95kY1z58SmwJXij0qdLokvJLNNGFQneKt8tyryevuQZZZ4s2A+RqxSllyILKLFuQW4Nuc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
