travis:
  secure:
    BINSTAR_TOKEN: KPBsl4+E99ZMho2NEKovtcFxIqZkh2ltgSoxzqMzTrEagujgybGU38nAg+zB0LsiIy2PSDjy4rqnJ2DlSv692jqm8cidkcGA/zTkNkw2wpcXkQgHixZVkqbsM8sGURUpnmsYqp26AgU+AaLp7208yjYhTazkfThimNJzTMYvgzhotT8apRmK2r13zrTETijqOYLjzCT+IOwFreSnBb/VA84zTf5GsGlVAhCxVY4MxlIe/5dah6tr5HLX4pHM9LBHW9ODkb5dw0YLmpY1TlXJWVjYsSUGcc+JFJP/tBwdzd7Vktg+TGNOQ1wVcdFRG6aYFV/ZwR9nfBTNM7nd5TiXEoGoiJ281nkrCoFzseBqGy9v/JVzx/N2nN5z17k4agwtWVkmj7G4gHWEOz86msF8mE8p9xt2ONEZYF2Bn+prGw+XZKRbpWDYRmRHnOSOFdX9V/XiWESc7Vxqmbl0eecqqwinaFKz8RHU61H65SeZZQo8iPN9lWUDIK9DRZ2syJ2RFMaz2GsQo9Lec9+OfQhwCLak9oG7xLFuaDL9spO4j6AC87TUPRGWPJsgmBv6KuC9ZUEQ1KQsxHyxEhg0KmXxeT1R+eYEQUPqN2Efcbh5386mLw+IqI3UFfGh3nTS2Z53k4Bz1kYdl+f8nnZjlW+PwquW9p2naLKk1KFn5iBLgNo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
