travis:
  secure:
    BINSTAR_TOKEN: brk3BKZFHmdydDvCipmhsO9PaGKMA0G1z+CkIydS1spq9Ir4rraberAFSpH33hxz3qj31Qa9topIsUfqsDvWi0QsoPXmCJvpsK88XpI2vB51Ezt5XbInvCLSBx04W6yKsqG31LH4vKdWT5untvRxi4I5Fqh5QvOtIzA/8HCgHUqWGe0s9VEl65JNxwNhoVH8IpGQ44xdQ5HNNjTk0K+ehinoJwkfkcI0wjzPXih9JekXEXJXUOJAqOfmDAqJTl4g9BWa6s93Bd2FM78hMYHOw36SAouSsacfI8TtoMn08SwOFo/xU0hblxBJJZ80GdVOux2OVsBIG4bYMs3B2NooEIm3NBPR5j2y4qUkk3hIEJCYMw4o8ktCdKUOZVOx4Km6OSn5uYXUd50RXiODSxGz6z9YySWtjotfi+Oah7JlhKwQWS6ZVv8IF016OShYDEjKSgVvkCm6Lpfa5OGuEwCn1mAg66LEV+4aoVV2khf4iejBdX5uOg3l9ZRTTEw4vIDctQrVtPYpYhpMINM4DddMwGTvuGBMPDAF1M5nELC8G6spQS7qx9DU2PgeUJXnOnachc8+yQUgtS04hcx0/4arETFbYLWYUvjQDAQZmxxERnWbFk2z6hq8V+RRLYL6zaJFquBf6ZsPq7+CdqJlEc2CZ9WSlgvWoA+N8eCuwK/ZJmE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
